### ISSUE TITLE
Releases up to date?  

### ISSUE THREAD

**Issue by JustinG512** [charlie1972/swgoh-automation#9]
Contact me on discord if you have a minute!  I'd love to help!

**Comment by charlie1972** [comment]
Hi, I'm open to contributions. What can you do to help?

**Comment by JustinG512** [comment]
Is anything posted to releases to try this out, or is it missing on my end? 
_How to run it from the release
Get the archive at: https://github.com/charlie1972/swgoh-automation/releases
Extract it and run the executable_

**Comment by charlie1972** [comment]
You are not mistaken. There is no release yet. I'm not comfortable enough to release it in executable form. Feel free to build the application, if you can!
